# Generated by Django 4.2.15 on 2024-08-21 09:53

from django.db import migrations

def seed_departments(apps, schema_editor):
    department = apps.get_model('clearance', 'Department')
    departments = [
        {"name": "Bursary", "code": "BS"},
        {"name": "Department", "code": "DD"},
        {"name": "Library", "code": "LB"},
        {"name": "Information and Communication Technology", "code": "ICT"},
        {"name": "Academic Affairs", "code": "AA"},
        {"name": "Medical Center", "code": "MC"},
        {"name": "College Office", "code": "CO"},
    ]
    for dept in departments:
        department.objects.create(name=dept["name"], code=dept["code"])

class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_departments),
    ]
