# Generated by Django 4.2.15 on 2024-08-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0003_remove_student_department'),
    ]

    operations = [
    ]
