# Generated by Django 4.2.15 on 2024-08-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0004_seed_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
