# Generated by Django 4.2.15 on 2024-08-21 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0007_alter_admin_id_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='00', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DepartmentClearance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clearance_start_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_cleared', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='clearance.department', to_field='code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='departmentClearance',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='clearance.departmentclearance'),
            preserve_default=False,
        ),
    ]
