# Generated by Django 4.2.15 on 2024-08-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0008_student_department_departmentclearance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='departmentClearance',
            new_name='department_clearance',
        ),
    ]
