# Generated by Django 4.2.15 on 2024-08-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0009_rename_departmentclearance_student_department_clearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department_clearance',
        ),
    ]
