# Generated by Django 4.2.15 on 2024-08-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0011_student_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
    ]
