# Generated by Django 4.2.15 on 2024-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0012_remove_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='thomasbenjamineghan@gmail.com', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
